scoring:
  thresholds:
    low: 0.20
    high: 0.60

  weights:
    stats: 0.10
    strings: 0.30
    binwalk: 0.15

  hard_rules:
    has_telnetd_min_level: "cve_conhecida"
    has_debug_account_min_level: "cve_conhecida"
    hardcoded_passwords_min_level: "cve_conhecida"
